backend/modules/service/controllers/DefaultController.php
<?php

namespace backend\modules\service\controllers;

use common\models\ServiceStep;
use Yii;
use common\models\Service;
use yii\data\ActiveDataProvider;
use yeesoft\controllers\admin\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DefaultController implements the CRUD actions for Service model.
 */
class DefaultController extends BaseController
{

    public $modelClass = 'common\models\Service';
    public $modelSearchClass = 'common\models\search\ServiceSearch';

    protected function getRedirectPage($action, $model = null)
    {
        switch ($action) {
            case 'update':
                return ['update', 'id' => $model->id];
                break;
            case 'create':
                return ['update', 'id' => $model->id];
                break;
            default:
                return parent::getRedirectPage($action, $model);
        }
    }

    /**
     * Displays a single Service model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ServiceStep::find()->where(['service_id' => $id])->orderBy('position, module_id'),
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
        ]);
    }


}

backend/modules/service/controllers/OrderController.php
<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 28.02.2018
 * Time: 13:50
 */

namespace backend\modules\service\controllers;


use common\models\Order;
use yeesoft\controllers\admin\BaseController;
use yii\data\ActiveDataProvider;

class OrderController extends BaseController
{
    public $modelClass = 'common\models\Order';
    public $modelSearchClass = 'common\models\search\CategorySearch';

    public function actionIndex(){
        $dataProvider = new ActiveDataProvider([
            'query' => Order::find(),
        ]);
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionView($id){
        $model = $this->findModel($id);
        return $this->render('view', compact('model'));
    }


}

backend/modules/service/controllers/StepController.php
<?php

namespace backend\modules\service\controllers;

use yeesoft\controllers\admin\BaseController;
use Yii;
use common\models\ServiceStep;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StepController implements the CRUD actions for ServiceStep model.
 */
class StepController extends BaseController
{

    public $modelClass = 'common\models\ServiceStep';
    public $modelSearchClass = 'common\models\search\ServiceStepSearch';

    protected function getRedirectPage($action, $model = null)
    {
        switch ($action) {
            case 'update':
                return ['update', 'id' => $model->id];
                break;
            case 'create':
                return ['update', 'id' => $model->id];
                break;
            default:
                return parent::getRedirectPage($action, $model);
        }
    }

    public function actionDuplicate($id){
        $model = ServiceStep::findOne($id);

        $new = new ServiceStep();
        $new->attributes = $model->attributes;
        $new->id = null;
        $new->save();
        return $this->redirect(['default/view', 'id' => $model->service_id]);
    }


}

backend/modules/service/views/default/_form.php
<?php

use yeesoft\helpers\Html;
use yeesoft\widgets\ActiveForm;
use yeesoft\widgets\LanguagePills;

/* @var $this yii\web\View */
/* @var $model common\models\Service */
/* @var $form yeesoft\widgets\ActiveForm */
?>

<div class="service-form">

    <?php $form = ActiveForm::begin([
        'id' => 'service-form',
        'validateOnBlur' => false,
    ]); ?>

    <div class="row">

        <div class="col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    <?php if ($model->isMultilingual()): ?>
                        <?= LanguagePills::widget() ?>
                    <?php endif; ?>

                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

                    <?=$form->field($model, 'description')->textarea()?>

                    <?= $form->field($model, 'icon')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'status')->checkbox() ?>

                    <?= $form->field($model, 'is_main')->checkbox() ?>

                    <?= $form->field($model, 'category_id')->dropDownList(\common\models\Category::map(), ['prompt' => Yii::t('app', '-- none --')]) ?>

                    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>


                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="record-info">

                        <div class="form-group">
                            <?php if ($model->isNewRecord): ?>
                                <?= Html::submitButton(Yii::t('yee', 'Create'), ['class' => 'btn btn-primary']) ?>
                                <?= Html::a(Yii::t('yee', 'Cancel'), ['index'], ['class' => 'btn btn-default',]) ?>
                            <?php else: ?>
                                <?= Html::submitButton(Yii::t('yee', 'Save'), ['class' => 'btn btn-primary']) ?>
                                <?= Html::a(Yii::t('yee', 'Delete'), ['delete', 'id' => $model->id], [
                                    'class' => 'btn btn-default',
                                    'data' => [
                                        'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                        'method' => 'post',
                                    ],
                                ])
                                ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

backend/modules/service/views/default/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Service */

$this->title = Yii::t('app', 'Create Service');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="service-create">
    <h3 class="lte-hide-title"><?= Html::encode($this->title) ?></h3>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/service/views/default/index.php
<?php

use yeesoft\grid\GridPageSize;
use yeesoft\grid\GridView;
use yeesoft\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\ServiceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Services');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="service-index">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="lte-hide-title page-title"><?= Html::encode($this->title) ?></h3>
            <?= Html::a(Yii::t('yee', 'Add New'), ['create'], ['class' => 'btn btn-sm btn-primary']) ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            <div class="row">
                <div class="col-sm-6">
                </div>

                <div class="col-sm-6 text-right">
                    <?= GridPageSize::widget(['pjaxId' => 'page-grid-pjax']) ?>
                </div>
            </div>

            <?php Pjax::begin(); ?>                                    <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'bulkActionOptions' => [
                    'gridId' => 'page-grid',
                    'actions' => [
                        Url::to(['bulk-delete']) => Yii::t('yee', 'Delete'),
                    ]
                ],
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yeesoft\grid\CheckboxColumn', 'options' => ['style' => 'width:10px']],
                    [
                        'class' => 'yeesoft\grid\columns\TitleActionColumn',
                        'controller' => '/service/default',
                        'title' => function (common\models\Service $model) {
                            return Html::a($model->name, ['view', 'id' => $model->id], ['data-pjax' => 0]);
                        },
                    ],

//                    'id',
                    'description:ntext',
                    'icon',
                    'color',
                    'status:status',
                    'is_main:boolean',
                    // 'category_id',
                    // 'code',

//                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
            <?php Pjax::end(); ?>        </div>
    </div>
</div>

backend/modules/service/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Service */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Service',
]) . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="service-create">
    <h3 class="lte-hide-title"><?= Html::encode($this->title) ?></h3>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/service/views/default/view.php
<?php

use common\models\ServiceStep;
use yeesoft\grid\GridPageSize;
use yeesoft\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model common\models\Service */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="service-view">

    <h3 class="lte-hide-title"><?= Html::encode($this->title) ?></h3>

    <div class="panel panel-default">
        <div class="panel-body">
            <?= Html::a(Yii::t('yee', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary']) ?>
            <?= Html::a(Yii::t('yee', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-sm btn-default',
                'data' => [
                    'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
            <?= Html::a(Yii::t('yee', 'Add New'), ['create'], ['class' => 'btn btn-sm btn-primary pull-right']) ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'name',
                    'icon',
                    'color:color',
                    'description:ntext',
                    'time',
                    'cost',
                    'status:status',
                    'is_main:boolean',
                    'category_id',
                    'code',
                ],
            ]) ?>

        </div>
    </div>

    <h3 class="lte-hide-title"><?= Yii::t('app', 'Service Steps') ?></h3>
    <div class="panel panel-default">
        <div class="panel-body">
            <?= Html::a(Yii::t('yee', 'Add New'), ['step/create', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary pull-right']) ?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                </div>

                <div class="col-sm-6 text-right">
                    <?= GridPageSize::widget(['pjaxId' => 'post-grid-pjax']) ?>
                </div>
            </div>

            <?php Pjax::begin(); ?>
            <?= GridView::widget([
                'bulkActionOptions' => [
                    'gridId' => 'post-grid',
                    'actions' => [
                        Url::to(['bulk-activate']) => Yii::t('yee', 'Publish'),
                        Url::to(['bulk-deactivate']) => Yii::t('yee', 'Unpublish'),
                        Url::to(['bulk-delete']) => Yii::t('yii', 'Delete'),
                    ]
                ],
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yeesoft\grid\CheckboxColumn', 'options' => ['style' => 'width:10px']],
                    [
                        'class' => 'yeesoft\grid\columns\TitleActionColumn',
                        'controller' => '/service/step',
                        'buttons' => [
                            'duplicate' => function ($url, ServiceStep $model) {
                                return Html::a(Yii::t('yee', 'Duplicate'), ['step/duplicate', 'id' => $model->id]);
                            }
                        ],
                        'buttonsTemplate' => '{update} {duplicate} {view} {delete} ',
                        'title' => function (ServiceStep $model) {
                            return Html::a($model->title, ['step/view', 'id' => $model->id], ['data-pjax' => 0]);
                        },
                    ],
                    'type',
                    'step',
                    'module_name',
                    'position',
                    'status:status',

                ],
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>